// MTQΣ — AI Policy Briefing (P1-B)
// Renders the latest COO-voice AI monetary policy briefing pulled from
// /api/ai/briefing → { briefing, generatedAt, model, sources, disclaimer }.
//
// The briefing is generated by Gemini (gemini-2.0-flash) from the live
// snapshot and cached 60s server-side. This component fetches on mount,
// polls every 60s, and provides a manual refresh button. The model badge
// (top-right Pill) is gold for real Gemini, muted for fallback-rules,
// rose for error/disabled. The body uses whitespace-pre-wrap so the
// model's paragraph breaks (\n\n) render naturally. The briefing text
// is wrapped in AnimatePresence keyed by generatedAt so a fresh briefing
// fades in cleanly.
//
// The component never throws on API 500 — it shows a rose-tinted error
// panel with a retry button instead. When model === 'disabled', it shows
// an amber-tinted "AI briefing disabled by feature flag" panel.
//
// Brand: obsidian + gold, font-mono on timestamps, lucide icons (no emojis),
// Panel + Reveal + Pill + GlowDot from the primitives. NO indigo, NO blue.

"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, RefreshCw, AlertCircle } from "lucide-react";
import { Panel, Reveal, Pill, GlowDot, Skeleton } from "./primitives";
import { fmtAgo } from "./format";

/* ---------- API shape contract (must match P1-A backend) ---------- */
interface BriefingResponse {
  briefing: string;
  generatedAt: number;
  model: string;
  sources: string[];
  disclaimer: string;
}

/* ---------- Model badge tone: gold / muted / rose ---------- */
function modelTone(model: string | null | undefined): "gold" | "muted" | "rose" {
  if (!model) return "muted";
  if (model === "disabled" || model === "error") return "rose";
  if (model.startsWith("fallback")) return "muted";
  return "gold"; // real model (gemini-2.0-flash, llama-3.3-70b, etc.)
}

/* ---------- Split briefing into paragraphs (show ALL model text) ---------- */
function splitParagraphs(briefing: string): string[] {
  // The model returns text with \n\n paragraph breaks. If there are
  // explicit paragraph markers, honour them too. Otherwise, fall back
  // to a single paragraph block. We always show every paragraph the
  // model returned — never truncate or hide.
  const trimmed = briefing?.trim() ?? "";
  if (!trimmed) return [];
  // Split on blank line(s) — handles \n\n, \n\r\n, etc.
  const paragraphs = trimmed
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);
  return paragraphs.length > 0 ? paragraphs : [trimmed];
}

/* ---------- AIPolicyBriefing component ---------- */
export function AIPolicyBriefing({ className = "" }: { className?: string }) {
  const [data, setData] = useState<BriefingResponse | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const mountedRef = useRef(true);

  const fetchBriefing = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/ai/briefing", { cache: "no-store" });
      if (!res.ok) {
        // Never throw on 500 — surface as error state.
        throw new Error(`briefing ${res.status}`);
      }
      const json = (await res.json()) as BriefingResponse;
      if (!mountedRef.current) return;
      // Defensive: backend should always return these fields. If the
      // backend returned an error-shape (model === "error"), keep the
      // raw payload but flip the error state so the rose panel shows.
      if (json?.model === "error" || !json?.briefing) {
        setData(json ?? null);
        setError(json?.briefing ? null : "Briefing payload missing");
      } else {
        setData(json);
      }
    } catch (e) {
      if (!mountedRef.current) return;
      setError(String(e instanceof Error ? e.message : e));
    } finally {
      if (mountedRef.current) setLoading(false);
    }
  }, []);

  useEffect(() => {
    mountedRef.current = true;
    fetchBriefing();
    // Poll every 60s — the backend caches 60s anyway, so this matches
    // the cache lifetime without spamming the upstream model.
    const id = setInterval(fetchBriefing, 60_000);
    return () => {
      mountedRef.current = false;
      clearInterval(id);
    };
  }, [fetchBriefing]);

  const tone = modelTone(data?.model);
  const paragraphs = data ? splitParagraphs(data.briefing) : [];

  /* ---------- Disabled state — amber panel ---------- */
  const renderDisabled = () => (
    <div className="rounded-md border border-mtqs-amber/40 bg-mtqs-amber/5 p-4 flex items-start gap-3">
      <AlertCircle className="h-4 w-4 text-mtqs-amber shrink-0 mt-0.5" aria-hidden="true" />
      <div>
        <div className="text-sm font-medium text-mtqs-gold">
          AI briefing disabled by feature flag
        </div>
        <p className="mt-1 text-[0.72rem] text-muted-foreground leading-relaxed">
          The <span className="font-mono text-mtqs-gold">AI_BRIEFING_ENABLED</span> flag is off.
          Enable it on the server to render the live COO-voice monetary policy briefing.
        </p>
      </div>
    </div>
  );

  /* ---------- Error state — rose panel + retry ---------- */
  const renderError = () => (
    <div className="rounded-md border border-mtqs-rose/40 bg-mtqs-rose/5 p-4">
      <div className="flex items-start gap-3">
        <AlertCircle className="h-4 w-4 text-mtqs-rose shrink-0 mt-0.5" aria-hidden="true" />
        <div className="flex-1 min-w-0">
          <div className="text-sm font-medium text-mtqs-rose">
            Briefing unavailable
          </div>
          <p className="mt-1 text-[0.72rem] text-muted-foreground leading-relaxed break-words">
            {error ?? "Unknown error"}
          </p>
        </div>
        <button
          onClick={fetchBriefing}
          disabled={loading}
          className="shrink-0 inline-flex items-center gap-1.5 rounded-md border border-mtqs-rose/30 bg-mtqs-rose/5 px-2.5 py-1.5 text-[0.7rem] font-medium text-rose-200 hover:bg-mtqs-rose/[0.12] transition disabled:opacity-50"
        >
          <RefreshCw className={`h-3 w-3 ${loading ? "animate-spin" : ""}`} aria-hidden="true" />
          Retry
        </button>
      </div>
    </div>
  );

  /* ---------- Loading skeleton — 3 pulsing gray bars ---------- */
  const renderSkeleton = () => (
    <div className="space-y-2.5" aria-hidden="true">
      <Skeleton className="h-3 w-[92%]" />
      <Skeleton className="h-3 w-[88%]" />
      <Skeleton className="h-3 w-[80%]" />
    </div>
  );

  return (
    <Reveal>
      <Panel className={`p-5 sm:p-6 ${className}`}>
        {/* ---------- Header row ---------- */}
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between mb-4">
          <div className="space-y-1.5 min-w-0">
            <div className="flex items-center gap-2">
              <Sparkles className="h-3.5 w-3.5 text-mtqs-gold/85" aria-hidden="true" />
              <span className="text-[0.6rem] uppercase tracking-[0.22em] text-mtqs-gold/85">
                AI · COO Briefing
              </span>
            </div>
            <h3 className="text-base font-semibold text-foreground">
              Monetary Policy Briefing
            </h3>
            <p className="text-[0.72rem] text-muted-foreground/75 leading-relaxed">
              Generated by Gemini from the live snapshot. Informational only — not financial advice.
            </p>
          </div>

          {/* Top-right: model badge + refresh */}
          <div className="flex items-center gap-2 shrink-0">
            <Pill tone={tone} className="font-mono">
              <GlowDot
                color={tone === "gold" ? "gold" : tone === "rose" ? "rose" : "amber"}
                size="h-1.5 w-1.5"
              />
              {data?.model ?? "—"}
            </Pill>
            <button
              onClick={fetchBriefing}
              disabled={loading}
              aria-label="Refresh briefing"
              className="inline-flex items-center justify-center rounded-md border border-border bg-black/[0.03] h-8 w-8 text-muted-foreground hover:text-foreground hover:bg-black/[0.06] transition disabled:opacity-50"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} aria-hidden="true" />
            </button>
          </div>
        </div>

        {/* ---------- Body ---------- */}
        <div className="min-h-[6rem]">
          {error ? (
            renderError()
          ) : data?.model === "disabled" ? (
            renderDisabled()
          ) : loading && !data ? (
            renderSkeleton()
          ) : (
            <AnimatePresence mode="wait" initial={false}>
              <motion.div
                key={data?.generatedAt ?? "initial"}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -6 }}
                transition={{ duration: 0.3 }}
                className="space-y-3"
              >
                {paragraphs.length === 0 ? (
                  <p className="text-[0.82rem] text-muted-foreground italic leading-relaxed">
                    No briefing text returned.
                  </p>
                ) : (
                  paragraphs.map((p, i) => (
                    <p
                      key={i}
                      className="whitespace-pre-wrap leading-relaxed text-[0.85rem] text-foreground/90"
                    >
                      {p}
                    </p>
                  ))
                )}
              </motion.div>
            </AnimatePresence>
          )}
        </div>

        {/* ---------- Footer: generated-at · sources · disclaimer ---------- */}
        {data && !error && data.model !== "disabled" && (
          <div className="mt-4 pt-3 border-t border-border space-y-1">
            <div className="flex flex-wrap items-center gap-x-2 gap-y-1 text-[0.68rem] font-mono tabular-nums text-muted-foreground/75">
              <GlowDot color="gold" size="h-1.5 w-1.5" />
              <span>
                Generated {fmtAgo(data.generatedAt)}
              </span>
              {data.sources && data.sources.length > 0 && (
                <>
                  <span className="text-muted-foreground/40">·</span>
                  <span>
                    Sources: {data.sources.join(", ")}
                  </span>
                </>
              )}
            </div>
            {data.disclaimer && (
              <p className="text-[0.62rem] text-muted-foreground/55 leading-relaxed">
                {data.disclaimer}
              </p>
            )}
          </div>
        )}
      </Panel>
    </Reveal>
  );
}

export default AIPolicyBriefing;
