// GET /api/ai/briefing
//
// Returns a 3-paragraph COO-voice briefing of the live MTQΣ snapshot.
// Generated by Gemini 2.0 Flash (server-side) with a 60s in-memory cache.
// If AI_BRIEFING_ENABLED=false → HTTP 503 { model: "disabled" }.
// If Gemini errors / no key → returns a deterministic fallback briefing
// (model: "fallback-rules") so the pilot stays fully functional.

import { NextResponse } from "next/server";
import { getSnapshot } from "@/lib/mtq/pilot-state";
import { generateBriefing } from "@/lib/ai/policy-briefer";
import { AI_BRIEFING_ENABLED } from "@/lib/ai/keys";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export async function GET() {
  if (!AI_BRIEFING_ENABLED) {
    return NextResponse.json(
      { error: "AI feature disabled", model: "disabled" },
      { status: 503 },
    );
  }
  try {
    const snapshot = await getSnapshot();
    const result = await generateBriefing(snapshot);
    return NextResponse.json(result);
  } catch (e) {
    return NextResponse.json(
      { error: String(e), model: "error" },
      { status: 500 },
    );
  }
}
