// GET /api/ai/risk-signals
//
// Returns 2-5 risk signals (JSON array) generated by Groq
// llama-3.3-70b-versatile (server-side) from the live snapshot, with a 15s
// in-memory cache. Each signal: { severity, title, detail, source }.
//
// If AI_RISK_SIGNALS_ENABLED=false → HTTP 503 { model: "disabled" }.
// If Groq errors / no key → returns deterministic rule-based signals
// (model: "fallback-rules").

import { NextResponse } from "next/server";
import { getSnapshot } from "@/lib/mtq/pilot-state";
import { generateRiskSignals } from "@/lib/ai/risk-signals";
import { AI_RISK_SIGNALS_ENABLED } from "@/lib/ai/keys";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export async function GET() {
  if (!AI_RISK_SIGNALS_ENABLED) {
    return NextResponse.json(
      { error: "AI feature disabled", model: "disabled" },
      { status: 503 },
    );
  }
  try {
    const snapshot = await getSnapshot();
    const result = await generateRiskSignals(snapshot);
    return NextResponse.json(result);
  } catch (e) {
    return NextResponse.json(
      { error: String(e), model: "error" },
      { status: 500 },
    );
  }
}
