// GET /api/ai/risk-signals
//
// Returns 2-5 risk signals (JSON array) generated by Groq
// llama-3.3-70b-versatile (server-side) from the live snapshot, with a 15s
// in-memory cache. Each signal: { severity, title, detail, source }.
//
// If AI_RISK_SIGNALS_ENABLED=false → HTTP 503 { model: "disabled" }.
// If Groq errors / no key → returns deterministic rule-based signals
// (model: "fallback-rules").
//
// Rate-limited at 5 req/IP/min (RATE_LIMITS.ai) — every hit burns a Groq
// token, so this is stricter than /api/health.

import { NextResponse } from "next/server";
import { getSnapshot } from "@/lib/mtq/pilot-state";
import { generateRiskSignals } from "@/lib/ai/risk-signals";
import { AI_RISK_SIGNALS_ENABLED } from "@/lib/ai/keys";
import { rateLimit, getClientIP } from "@/lib/mtq/rate-limit";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export async function GET(req: Request) {
  const ip = getClientIP(req);
  const rl = await rateLimit(ip, "ai");
  if (!rl.allowed) {
    return NextResponse.json(
      { error: "Rate limit exceeded", retryAfter: 60 },
      {
        status: 429,
        headers: {
          "Retry-After": String(Math.ceil((rl.resetAt - Date.now()) / 1000)),
        },
      },
    );
  }
  if (!AI_RISK_SIGNALS_ENABLED) {
    return NextResponse.json(
      { error: "AI feature disabled", model: "disabled" },
      {
        status: 503,
        headers: { "X-RateLimit-Remaining": String(rl.remaining) },
      },
    );
  }
  try {
    const snapshot = await getSnapshot();
    const result = await generateRiskSignals(snapshot);
    return NextResponse.json(result, {
      headers: { "X-RateLimit-Remaining": String(rl.remaining) },
    });
  } catch (e) {
    return NextResponse.json(
      { error: String(e), model: "error" },
      {
        status: 500,
        headers: { "X-RateLimit-Remaining": String(rl.remaining) },
      },
    );
  }
}
