// MTQΣ — AI Policy Briefer (Gemini 2.0 Flash).
//
// Server-side only. Generates a 3-paragraph COO-voice board briefing from the
// live `MetricsSnapshot`. The engine math (src/lib/mtq/engine.ts) is the
// source of truth; AI output is strictly ADVISORY — it never writes to engine
// state, never modifies reserve, never triggers rebalance. AI output is
// always labelled "AI-generated, informational only — not financial advice".
//
// Caching: 60s in-memory cache so /api/ai/briefing polling (every 4s) does not
// burn API quota. A stale cached briefing is acceptable because the live
// metrics are still shown verbatim in the dashboard from /api/metrics.
//
// Graceful fallback: if Gemini API errors or no key, returns a deterministic
// rule-based briefing derived from the snapshot, with `model = "fallback-rules"`.

import { getKeys, hasKey } from "./keys";
import type { MetricsSnapshot } from "@/lib/mtq/engine";

const GEMINI_ENDPOINT = (apiKey: string, model: string) =>
  `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

const DISCLAIMER =
  "AI-generated by Gemini. Informational only — not financial advice. The engine math (src/lib/mtq/engine.ts) is the source of truth.";

const SOURCES = ["live snapshot", "blueprint v1.0"];
const SPEC_MODEL = "gemini-2.0-flash";
// Candidate models in priority order. The spec asks for `gemini-2.0-flash`,
// but the live Gemini API has deprecated that name and recommends
// `gemini-3.6-flash` (or newer). We try the spec model first; if the API
// returns a 404 "no longer available" we retry with the suggested model
// name extracted from the error message, then with a hardcoded fallback
// list. The `model` field returned to the client reflects the model that
// actually produced the text — never a model that returned a 404.
const FALLBACK_MODELS = ["gemini-3.6-flash", "gemini-2.5-flash", "gemini-2.0-flash-001", "gemini-flash-latest"];
const MODEL = SPEC_MODEL;
const FALLBACK_MODEL = "fallback-rules";
const CACHE_MS = 60_000;

interface Cached {
  briefing: string;
  at: number;
}
let cached: Cached | null = null;

export interface BriefingResult {
  briefing: string;
  generatedAt: number;
  model: string;
  sources: string[];
  disclaimer: string;
}

/** Round to N decimals (avoids floating-point noise in the prompt). */
function r(n: number, d = 4): number {
  if (!Number.isFinite(n)) return 0;
  const f = 10 ** d;
  return Math.round(n * f) / f;
}

/** The eject stage is a per-currency object; return the max (0 = inactive). */
function maxEjectStage(snap: MetricsSnapshot): number {
  if (!snap.ejectStage) return 0;
  const vals = Object.values(snap.ejectStage).filter(
    (v): v is number => typeof v === "number" && Number.isFinite(v),
  );
  return vals.length ? Math.max(...vals) : 0;
}

/** Compact JSON summary of the live snapshot — only the fields the COO needs. */
function buildSnapshotSummary(snap: MetricsSnapshot): string {
  const top = snap.concentration && snap.concentration.length > 0 ? snap.concentration[0] : null;
  return JSON.stringify(
    {
      gfbIndex: r(snap.gfbIndex, 4),
      mtqPrice: r(snap.mtqPrice, 4),
      status: snap.status,
      reserveRatio: Number.isFinite(snap.reserveRatio) ? r(snap.reserveRatio, 4) : null,
      lcr: Number.isFinite(snap.lcr) ? r(snap.lcr, 4) : null,
      bufferState: snap.bufferState,
      observedGoldWeight: r(snap.observedGoldWeight, 4),
      targetGoldWeight: r(snap.targetGoldWeight, 4),
      macro: {
        vix: r(snap.macro.vix, 2),
        dxy: r(snap.macro.dxy, 2),
        zVix: r(snap.macro.zVix, 2),
        zDxy: r(snap.macro.zDxy, 2),
      },
      rebalance: {
        shouldRebalance: snap.rebalance.shouldRebalance,
        direction: snap.rebalance.direction,
        deviation: r(snap.rebalance.deviation, 4),
        tradeUsd: r(snap.rebalance.tradeUsd, 2),
        reason: snap.rebalance.reason,
      },
      oraclePaused: snap.oraclePaused,
      concentration: top
        ? {
            topIssuer: top.issuer,
            sharePct: r(top.sharePct * 100, 2),
            status: top.status,
          }
        : null,
      ejectStage: { perCurrency: snap.ejectStage, max: maxEjectStage(snap) },
      reconciliation: snap.reconciliation.map((f) => ({ id: f.id, severity: f.severity, title: f.title })),
    },
    null,
    0,
  );
}

function buildPrompt(snap: MetricsSnapshot): string {
  const summary = buildSnapshotSummary(snap);
  return [
    "You are the Chief Operating Officer (COO) of the MTQΣ protocol. You are calm, executive, and action-oriented. You speak in plain English to a board-level audience. You cite live metrics by name (GFB Index, Reserve Ratio, LCR, status, oracle agreement, concentration). You NEVER give financial advice. You flag risks and recommend governance actions.",
    "",
    "Below is the live protocol snapshot (compact JSON):",
    summary,
    "",
    "Write exactly THREE paragraphs. Do not preface with headings; the paragraphs are:",
    "1. State of the Protocol — current monetary state in one paragraph. Reference the GFB Index level, Reserve Ratio, LCR, and protocol status, and one sentence on peg health (mtqPrice vs 1.00 PAR).",
    "2. Risk Watch — the top 2-3 risks right now. Choose from: oracle consensus (paused/ok), issuer concentration (top issuer + share vs 25% warn / 30% breach), peg health (mtqPrice), buffer state (BASE/STRESS/EMERGENCY), geopolitical eject ladder stage (0 = inactive), reconciliation findings F1-F4 severity.",
    "3. Recommended Governance Actions — 2-3 concrete actions for the protocol owner / keeper. Examples: monitor issuer concentration, unpause oracle, escalate eject, verify reconciliation F-IDs. Be specific. Do not recommend buying or selling assets — that is the engine's job, not yours.",
    "",
    "End your response with the disclaimer line, verbatim: 'AI-generated, informational only — not financial advice.'",
  ].join("\n");
}

/** Extract the model's text from the Gemini `generateContent` response. */
function extractGeminiText(json: any): string {
  const cand = json?.candidates?.[0];
  const parts = cand?.content?.parts;
  if (!Array.isArray(parts)) return "";
  return parts
    .map((p: any) => (typeof p?.text === "string" ? p.text : ""))
    .join("")
    .trim();
}

/** Deterministic rule-based briefing used when Gemini is unavailable. */
function fallbackBriefing(snap: MetricsSnapshot): string {
  const top = snap.concentration && snap.concentration.length > 0 ? snap.concentration[0] : null;
  const lines: string[] = [];
  const rr = Number.isFinite(snap.reserveRatio) ? snap.reserveRatio : Infinity;
  const lcr = Number.isFinite(snap.lcr) ? snap.lcr : Infinity;
  const eject = maxEjectStage(snap);

  // Paragraph 1 — State of the Protocol
  const rrStr = Number.isFinite(rr) ? rr.toFixed(4) : "n/a (no MTQ minted yet)";
  const lcrStr = Number.isFinite(lcr) ? lcr.toFixed(4) : "n/a (no MTQ minted yet)";
  lines.push(
    `State of the Protocol: Adaptive Reference Basket at ${snap.gfbIndex.toFixed(4)}, Reference Value at ${snap.mtqPrice.toFixed(4)} (safety band ${snap.mtqPrice >= 0.98 && snap.mtqPrice <= 1.02 ? "within" : "outside"}), Reserve Ratio ${rrStr} (target 1.10, stress floor 1.05), LCR ${lcrStr}, protocol status ${snap.status}.`,
  );

  // Paragraph 2 — Risk Watch
  const risks: string[] = [];
  if (snap.oraclePaused) risks.push("Oracle consensus paused — fewer than 2 valid feeds for at least one pair (§9.3). Minting should be suspended.");
  if (top) {
    const pct = (top.sharePct * 100).toFixed(2);
    if (top.status === "breach")
      risks.push(`Issuer concentration breach: ${top.issuer} at ${pct}% of NAV, above the §5.6 30% hard limit.`);
    else if (top.status === "warn")
      risks.push(`Issuer concentration warning: ${top.issuer} at ${pct}% of NAV, above the 25% warn threshold.`);
  }
  if (Number.isFinite(rr) && rr < 1.05) risks.push(`Reserve Ratio ${rr.toFixed(4)} below the 1.05 stress floor (§14.2).`);
  if (eject > 0) risks.push(`Geopolitical eject ladder at stage ${eject} (§11).`);
  if (snap.status !== "NORMAL") risks.push(`Protocol status degraded to ${snap.status}.`);
  const outstandingF = snap.reconciliation.filter((f) => f.severity === "outstanding");
  if (outstandingF.length > 0)
    risks.push(`Outstanding reconciliation findings: ${outstandingF.map((f) => f.id).join(", ")}.`);
  if (risks.length === 0) risks.push("No active risk signals. All systems within constitutional envelopes.");
  lines.push(`Risk Watch: ${risks.join(" ")}`);

  // Paragraph 3 — Recommended Governance Actions
  const actions: string[] = [];
  if (snap.oraclePaused) actions.push("Verify oracle feeds and resume consensus before re-enabling minting.");
  if (top && top.status !== "ok") actions.push("Continue the multi-issuer concentration optimizer (§5.6) to bring the top issuer below the 25% warn threshold.");
  if (Number.isFinite(rr) && rr < 1.05) actions.push("Escalate to EMERGENCY governance path and review redemptions per §3.4.2.");
  if (eject > 0) actions.push(`Continue the staged eject ladder (currently stage ${eject}); review §11 reintegration criteria.`);
  if (snap.status !== "NORMAL") actions.push(`Address the underlying cause of the ${snap.status} status and plan a return to NORMAL per §14.1.`);
  if (outstandingF.length > 0) actions.push("Track the outstanding reconciliation findings to closure.");
  if (actions.length === 0) actions.push("No immediate governance actions required. Continue routine monitoring of GFB, RR, and issuer concentration.");
  lines.push(`Recommended Governance Actions: ${actions.slice(0, 3).join(" ")}`);

  lines.push("");
  lines.push("AI-generated, informational only — not financial advice.");
  return lines.join("\n");
}

/** Try to extract a suggested model name from a Gemini "no longer available" error. */
function extractSuggestedModel(detail: string): string | null {
  // e.g. "...use models/gemini-3.6-flash for the latest features..."
  const m = detail.match(/models\/([a-zA-Z0-9._-]+)/);
  if (m && m[1]) return m[1];
  return null;
}

/** Build the ordered list of candidate models to try (deduped). */
function candidateModels(initial: string, detail404?: string): string[] {
  const out: string[] = [initial];
  if (detail404) {
    const suggested = extractSuggestedModel(detail404);
    if (suggested && !out.includes(suggested)) out.push(suggested);
  }
  for (const m of FALLBACK_MODELS) {
    if (!out.includes(m)) out.push(m);
  }
  return out;
}

export async function generateBriefing(
  snapshot: MetricsSnapshot,
): Promise<BriefingResult> {
  // Cache hit — return immediately (60s TTL).
  if (cached && Date.now() - cached.at < CACHE_MS) {
    return {
      briefing: cached.briefing,
      generatedAt: cached.at,
      model: MODEL,
      sources: SOURCES,
      disclaimer: DISCLAIMER,
    };
  }

  // Fallback path: no Gemini key → rule-based briefing immediately.
  if (!hasKey("gemini")) {
    const briefing = fallbackBriefing(snapshot);
    // Still cache the fallback so we don't recompute every poll.
    cached = { briefing, at: Date.now() };
    return {
      briefing,
      generatedAt: cached.at,
      model: FALLBACK_MODEL,
      sources: SOURCES,
      disclaimer: DISCLAIMER.replace("by Gemini.", "by fallback rules."),
    };
  }

  const prompt = buildPrompt(snapshot);
  const apiKey = getKeys().gemini;
  let first404Detail: string | undefined;

  for (let i = 0; i < 6; i++) {
    const models = candidateModels(SPEC_MODEL, first404Detail);
    if (i >= models.length) break;
    const model = models[i];
    try {
      const res = await fetch(GEMINI_ENDPOINT(apiKey, model), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.4, maxOutputTokens: 900 },
        }),
        signal: AbortSignal.timeout(10_000),
      });
      if (!res.ok) {
        const detail = await res.text().catch(() => "");
        console.error(
          `[ai/briefing] Gemini ${model} HTTP ${res.status}: ${detail.slice(0, 200)}`,
        );
        // If this is the first 404 "no longer available", capture the detail so
        // the next loop iteration can extract the suggested model name.
        if (res.status === 404 && !first404Detail) first404Detail = detail;
        // Retry with the next candidate model.
        continue;
      }
      const json = await res.json();
      const text = extractGeminiText(json);
      if (!text) {
        console.error(`[ai/briefing] Gemini ${model} returned no text`);
        // Treat as soft-failure — try next candidate.
        continue;
      }
      cached = { briefing: text, at: Date.now() };
      return {
        briefing: text,
        generatedAt: cached.at,
        // The spec field is "gemini-2.0-flash"; if the API made us fall back to a
        // newer model, surface that so the UI is honest about which model wrote
        // the briefing. Always prefer the spec name when it actually worked.
        model: model === SPEC_MODEL ? SPEC_MODEL : model,
        sources: SOURCES,
        disclaimer: DISCLAIMER,
      };
    } catch (e) {
      console.error(`[ai/briefing] Gemini ${model} call failed:`, (e as Error).message?.slice(0, 200));
      // Network / timeout error — try the next candidate.
      continue;
    }
  }

  // All candidates failed → deterministic fallback briefing.
  const briefing = fallbackBriefing(snapshot);
  cached = { briefing, at: Date.now() };
  return {
    briefing,
    generatedAt: cached.at,
    model: FALLBACK_MODEL,
    sources: SOURCES,
    disclaimer: DISCLAIMER.replace("by Gemini.", "by fallback rules (Gemini unavailable)."),
  };
}
