// MTQΣ — Sanctions / Entity Screen (Hugging Face NER).
//
// Server-side only. Extracts named entities (PER / ORG / LOC / MISC) from a
// text using the Hugging Face Inference API + the classic
// `dbmdz/bert-large-cased-finetuned-conll03-english` NER model. This is a
// fast, labelled NER screening helper — NOT a substitute for OFAC/EU/UN
// sanctions list checks. Every output carries that disclaimer.
//
// Filters: score ≥ 0.85; dedupe by surface word; map entity_group to a
// readable type.
//
// Graceful fallback: if HF is unavailable, no key, or the model is cold-loading,
// fall back to a simple regex that finds capitalized multi-word phrases —
// labelled `fallback-regex` so the UI can mark it clearly.

import { getKeys, hasKey } from "./keys";

const HF_ENDPOINT =
  "https://api-inference.huggingface.co/models/dbmdz/bert-large-cased-finetuned-conll03-english";
const HF_MODEL = "dbmdz/bert-large-cased-finetuned-conll03-english";
const FALLBACK_MODEL = "fallback-regex";

const DISCLAIMER =
  "AI-generated by Hugging Face NER. Informational only — not a substitute for OFAC/EU/UN sanctions list checks.";

const MAX_TEXT = 5000;

const GROUP_LABELS: Record<string, string> = {
  PER: "Person",
  ORG: "Organization",
  LOC: "Location",
  MISC: "Misc",
};

export interface Entity {
  text: string;
  type: string;
  start: number;
  end: number;
  score: number;
}

export interface ScreenResult {
  entities: Entity[];
  model: string;
  disclaimer: string;
}

interface HfEntity {
  entity_group?: string;
  score?: number;
  word?: string;
  start?: number;
  end?: number;
}

function sanitizeText(raw: string): string | null {
  if (typeof raw !== "string") return null;
  const stripped = raw.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "");
  const trimmed = stripped.trim();
  if (trimmed.length === 0) return null;
  if (trimmed.length > MAX_TEXT) return null;
  return trimmed;
}

/** Poor-man's NER regex fallback — finds capitalized multi-word phrases. */
function regexEntities(text: string): Entity[] {
  // Match 1-3 consecutive Capitalized Words, optionally joined by spaces/dashes.
  // Excludes the first word of a sentence ONLY when preceded by '. ' or '? ' or '! '.
  const re = /\b([A-Z][a-zA-Z'-]+(?:\s+[A-Z][a-zA-Z'-]+){0,2})\b/g;
  const seen = new Set<string>();
  const out: Entity[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    const phrase = m[1].trim();
    // Skip single-word common-sentence-starter false positives (English articles
    // can't be capitalized, but sentence starts like "The" / "This" / "It"
    // frequently match — filter them out so the fallback isn't too noisy).
    if (/^(The|This|That|These|Those|It|He|She|They|We|You|I|A|An|But|And|Or|So|Because|When|Where|Why|How|What|Who)$/.test(phrase)) {
      continue;
    }
    if (seen.has(phrase.toLowerCase())) continue;
    seen.add(phrase.toLowerCase());
    out.push({
      text: phrase,
      type: "Unknown (regex)",
      start: m.index,
      end: m.index + phrase.length,
      score: 0.5,
    });
  }
  return out;
}

export async function screenText(text: string): Promise<ScreenResult> {
  const clean = sanitizeText(text);
  if (!clean) {
    return {
      entities: [],
      model: FALLBACK_MODEL,
      disclaimer: DISCLAIMER.replace("by Hugging Face NER.", "by fallback regex (invalid input)."),
    };
  }

  if (!hasKey("huggingface")) {
    return {
      entities: regexEntities(clean),
      model: FALLBACK_MODEL,
      disclaimer: DISCLAIMER.replace("by Hugging Face NER.", "by fallback regex (no HF key)."),
    };
  }

  try {
    const res = await fetch(HF_ENDPOINT, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${getKeys().huggingface}`,
      },
      body: JSON.stringify({ inputs: clean }),
      signal: AbortSignal.timeout(15_000),
    });

    // HF returns 503 with `{ error: "Model ... is currently loading" }` on cold
    // start. The contract is to retry after a wait, but for the pilot we just
    // fall back to the regex (clearly labelled) so the UI stays responsive.
    if (res.status === 503) {
      const detail = await res.text().catch(() => "");
      console.warn(`[ai/screen] HF model cold-start (503): ${detail.slice(0, 120)}`);
      return {
        entities: regexEntities(clean),
        model: FALLBACK_MODEL,
        disclaimer: DISCLAIMER.replace("by Hugging Face NER.", "by fallback regex (HF model loading)."),
      };
    }
    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      console.error(`[ai/screen] HF HTTP ${res.status}: ${detail.slice(0, 200)}`);
      return {
        entities: regexEntities(clean),
        model: FALLBACK_MODEL,
        disclaimer: DISCLAIMER.replace("by Hugging Face NER.", "by fallback regex (HF API error)."),
      };
    }

    const json: unknown = await res.json();
    if (!Array.isArray(json)) {
      console.error("[ai/screen] HF returned non-array:", typeof json);
      return {
        entities: regexEntities(clean),
        model: FALLBACK_MODEL,
        disclaimer: DISCLAIMER.replace("by Hugging Face NER.", "by fallback regex (HF bad shape)."),
      };
    }

    // Filter: score ≥ 0.85, dedupe by surface word (case-insensitive).
    const seen = new Set<string>();
    const out: Entity[] = [];
    for (const e of json as HfEntity[]) {
      if (!e || typeof e !== "object") continue;
      const group = typeof e.entity_group === "string" ? e.entity_group.toUpperCase() : "";
      const score = typeof e.score === "number" ? e.score : 0;
      const word = typeof e.word === "string" ? e.word.replace(/^##/, "").trim() : "";
      if (score < 0.85) continue;
      if (!word) continue;
      const key = word.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      out.push({
        text: word,
        type: GROUP_LABELS[group] ?? (group || "Unknown"),
        start: typeof e.start === "number" ? e.start : -1,
        end: typeof e.end === "number" ? e.end : -1,
        score: Math.round(score * 1000) / 1000,
      });
    }
    return {
      entities: out,
      model: HF_MODEL,
      disclaimer: DISCLAIMER,
    };
  } catch (e) {
    console.error("[ai/screen] HF call failed:", (e as Error).message?.slice(0, 200));
    return {
      entities: regexEntities(clean),
      model: FALLBACK_MODEL,
      disclaimer: DISCLAIMER.replace("by Hugging Face NER.", "by fallback regex (HF unreachable)."),
    };
  }
}
